using IconGrid.ViewModels.Launcher;

namespace IconGrid.ViewModels
{
    public partial class MainViewModel
    {
        // ---------- Localization bindings ----------
        public string SettingsTitle => _localizationState.Get(Language, "SettingsTitle");
        public string IconsPerRowLabel => _localizationState.Get(Language, "IconsPerRow");
        public string IconRowSpacingLabel => _localizationState.Get(Language, "IconRowSpacing");
        public string StartWithWindowsLabel => _localizationState.Get(Language, "StartWithWindows");
        public string LastRowPaddingLabel => _localizationState.Get(Language, "LastRowPadding");
        public string IconSizeLabel => _localizationState.Get(Language, "IconSize");
        public string UiScaleLabel => _localizationState.Get(Language, "UiScale");
        public string AlwaysOnTopLabel => _localizationState.Get(Language, "AlwaysOnTop");
        public string FloatingIconTopmostLabel => _localizationState.Get(Language, "FloatingIconTopmost");
        public string ShowScrollButtonsLabel => _localizationState.Get(Language, "ShowScrollButtons");
        public string ShowDesktopIconLabel => _localizationState.Get(Language, "ShowDesktopIcon");
        public string StartDirectlyInLauncherLabel => _localizationState.Get(Language, "StartDirectlyInLauncher");
        public string StartDirectlyInLauncherDescription => _localizationState.Get(Language, "StartDirectlyInLauncherDescription");
        public string LanguageLabel => _localizationState.Get(Language, "Language");
        public string ResetDefaultsLabel => _localizationState.Get(Language, "ResetDefaults");
        public string EnableSlideUpAnimationLabel => _localizationState.Get(Language, "EnableSlideUpAnimation");
        public string WindowAnimationSpeedLabel => _localizationState.Get(Language, "WindowAnimationSpeed");
        public string EnableIconScrollLabel => _localizationState.Get(Language, "EnableIconScroll");
        public string CarouselViewLabel => _localizationState.Get(Language, "CarouselView");
        public string SettingsPlaceholderLabel => _localizationState.Get(Language, "SettingsPlaceholder");
        public string DevOverlayLabel => _localizationState.Get(Language, "DevOverlayLabel");
        public string ChangeIconLabel => _localizationState.Get(Language, "ChangeIcon");
        public string WindowsIconsLabel => _localizationState.Get(Language, "WindowsIcons");
        public string OpenLabel => _localizationState.Get(Language, "Open");
        public string CloseLabel => _localizationState.Get(Language, "Close");
        public string MinimizeLabel => _localizationState.Get(Language, "Minimize");
        public string SelectLabel => _localizationState.Get(Language, "Select");
        public string ExitLabel => _localizationState.Get(Language, "Exit");
        public string ExitFullyLabel => _localizationState.Get(Language, "ExitFully");
        public string RunAsAdminLabel => _localizationState.Get(Language, "RunAsAdmin");
        public string OpenFileLocationLabel => _localizationState.Get(Language, "OpenFileLocation");
        public string CopyPathLabel => _localizationState.Get(Language, "CopyPath");
        public string ResetIconLabel => _localizationState.Get(Language, "ResetIcon");
        public string RenameLabel => _localizationState.Get(Language, "Rename");
        public string RemoveLabel => _localizationState.Get(Language, "Remove");
        public string LayoutsLabel => _localizationState.Get(Language, "MoreLayouts");
        public string MoreSettingsLabel => _localizationState.Get(Language, "MoreSettings");
        public string HelpLabel => _localizationState.Get(Language, "MoreHelp");
        public string AboutLabel => _localizationState.Get(Language, "MoreAbout");
        public string MonitorNetworkLabel => _localizationState.Get(Language, "MonitorNetworkLabel");
        public string MonitorDownloadLabel => _localizationState.Get(Language, "MonitorDownloadLabel");
        public string MonitorUploadLabel => _localizationState.Get(Language, "MonitorUploadLabel");
        public string MonitorCpuLabel => _localizationState.Get(Language, "MonitorCpuLabel");
        public string MonitorGpuLabel => _localizationState.Get(Language, "MonitorGpuLabel");
        public string HomeTitle => _localizationState.Get(Language, "HomeTitle");
        public string HomeIntroLine1 => _localizationState.Get(Language, "HomeIntroLine1");
        public string HomeIntroLine2 => _localizationState.Get(Language, "HomeIntroLine2");
        public string SystemAndStartupTitle => _localizationState.Get(Language, "SystemAndStartupTitle");
        public string LanguageSectionTitle => _localizationState.Get(Language, "LanguageSectionTitle");
        public string LanguageSectionDescription => _localizationState.Get(Language, "LanguageSectionDescription");
        public string ToggleStatePrefixText => _localizationState.Get(Language, "ToggleStatePrefix");
        public string ToggleStateOnText => _localizationState.Get(Language, "ToggleStateOn");
        public string ToggleStateOffText => _localizationState.Get(Language, "ToggleStateOff");
        public string AlwaysOnTopDescription => _localizationState.Get(Language, "AlwaysOnTopDescription");
        public string ShowScrollButtonsDescription => _localizationState.Get(Language, "ShowScrollButtonsDescription");
        public string DevOverlayDescription => _localizationState.Get(Language, "DevOverlayDescription");
        public string UiScaleDescription => _localizationState.Get(Language, "UiScaleDescription");
        public string LanguageOptionDanish => _localizationState.Get(Language, "LanguageOptionDanish");
        public string LanguageOptionEnglish => _localizationState.Get(Language, "LanguageOptionEnglish");
        public string ShortcutsTitle => _localizationState.Get(Language, "ShortcutsTitle");
        public string ShortcutsIntro => _localizationState.Get(Language, "ShortcutsIntro");
        public string ShortcutsAnimationTitle => _localizationState.Get(Language, "ShortcutsAnimationTitle");
        public string ShortcutsAnimationIntro => _localizationState.Get(Language, "ShortcutsAnimationIntro");
        public string ShortcutsAnimationToggle => _localizationState.Get(Language, "ShortcutsAnimationToggle");
        public string AboutTitleText => _localizationState.Get(Language, "AboutTitle");
        public string AboutIntroText => _localizationState.Get(Language, "AboutIntro");
        public string HelpTitleText => _localizationState.Get(Language, "HelpTitle");
        public string HelpIntroText => _localizationState.Get(Language, "HelpIntro");
        public string HelpDragDropText => _localizationState.Get(Language, "HelpDragDrop");
        public string HelpSensorsText => _localizationState.Get(Language, "HelpSensors");
        public string HelpTopBarText => _localizationState.Get(Language, "HelpTopBar");
        public string HelpMoreTipsText => _localizationState.Get(Language, "HelpMoreTips");
        public string LayoutTitleText => _localizationState.Get(Language, "LayoutTitle");
        public string LayoutIntroText => _localizationState.Get(Language, "LayoutIntro");
        public string LayoutPresetsTitleText => _localizationState.Get(Language, "LayoutPresetsTitle");
        public string LayoutPresetsIntroText => _localizationState.Get(Language, "LayoutPresetsIntro");
        public string LayoutFieldLabelText => _localizationState.Get(Language, "LayoutFieldLabel");
        public string LayoutRunNowText => _localizationState.Get(Language, "LayoutRunNow");
        public string LayoutSaveAsText => _localizationState.Get(Language, "LayoutSaveAs");
        public string LayoutSkipMinimizedText => _localizationState.Get(Language, "LayoutSkipMinimized");
        public string LayoutActiveScreenOnlyText => _localizationState.Get(Language, "LayoutActiveScreenOnly");
        public string LayoutReserveSlotTitleText => _localizationState.Get(Language, "LayoutReserveSlotTitle");
        public string LayoutReserveSlotIntroText => _localizationState.Get(Language, "LayoutReserveSlotIntro");
        public string LayoutReserveSlotToggleText => _localizationState.Get(Language, "LayoutReserveSlotToggle");
        public string LayoutChooseSlotText => _localizationState.Get(Language, "LayoutChooseSlot");
        public string LayoutPreviewPositionText => _localizationState.Get(Language, "LayoutPreviewPosition");
        public string LayoutSlotTipText => _localizationState.Get(Language, "LayoutSlotTip");
        public string LayoutPreviewTipText => _localizationState.Get(Language, "LayoutPreviewTip");
        public string HardwareNavTitleText => _localizationState.Get(Language, "HardwareNavTitle");
        public string HardwareBoardTitleText => _localizationState.Get(Language, "HardwareBoardTitle");
        public string HardwareBoardIntroText => _localizationState.Get(Language, "HardwareBoardIntro");
        public string HardwareCpuIntroText => _localizationState.Get(Language, "HardwareCpuIntro");
        public string HardwareGpuIntroText => _localizationState.Get(Language, "HardwareGpuIntro");
        public string HardwareMemoryTitleText => _localizationState.Get(Language, "HardwareMemoryTitle");
        public string HardwareMemoryIntroText => _localizationState.Get(Language, "HardwareMemoryIntro");
        public string HardwareModelLabelText => _localizationState.Get(Language, "HardwareModelLabel");
        public string HardwareSearchBoardLabelText => _localizationState.Get(Language, "HardwareSearchBoardLabel");
        public string HardwareBiosLabelText => _localizationState.Get(Language, "HardwareBiosLabel");
        public string HardwareCoresLabelText => _localizationState.Get(Language, "HardwareCoresLabel");
        public string HardwareThreadsLabelText => _localizationState.Get(Language, "HardwareThreadsLabel");
        public string HardwareLiveTempLabelText => _localizationState.Get(Language, "HardwareLiveTempLabel");
        public string HardwareLiveUsageLabelText => _localizationState.Get(Language, "HardwareLiveUsageLabel");
        public string HardwareLiveClockLabelText => _localizationState.Get(Language, "HardwareLiveClockLabel");
        public string HardwareBoostLabelText => _localizationState.Get(Language, "HardwareBoostLabel");
        public string HardwareVendorLabelText => _localizationState.Get(Language, "HardwareVendorLabel");
        public string HardwareVramLabelText => _localizationState.Get(Language, "HardwareVramLabel");
        public string HardwareLayoutLabelText => _localizationState.Get(Language, "HardwareLayoutLabel");
        public string HardwareTypeLabelText => _localizationState.Get(Language, "HardwareTypeLabel");
        public string HardwareSpeedLabelText => _localizationState.Get(Language, "HardwareSpeedLabel");
        public string HardwareTimingLabelText => _localizationState.Get(Language, "HardwareTimingLabel");
        public string HardwareModulesLabelText => _localizationState.Get(Language, "HardwareModulesLabel");
        public string HardwareSlotsLabelText => _localizationState.Get(Language, "HardwareSlotsLabel");
        public string HardwareVoltageLabelText => _localizationState.Get(Language, "HardwareVoltageLabel");

        public string PawnIoMissingMessage => _localizationState.PawnIoMissingMessage;

        public string PawnIoDownloadLink => _localizationState.PawnIoDownloadLink;

        private void NotifyLocalizationPropertiesChanged()
        {
            OnPropertyChanged(nameof(SettingsTitle));
            OnPropertyChanged(nameof(IconsPerRowLabel));
            OnPropertyChanged(nameof(IconRowSpacingLabel));
            OnPropertyChanged(nameof(StartWithWindowsLabel));
            OnPropertyChanged(nameof(LastRowPaddingLabel));
            OnPropertyChanged(nameof(IconSizeLabel));
            OnPropertyChanged(nameof(UiScaleLabel));
            OnPropertyChanged(nameof(AlwaysOnTopLabel));
            OnPropertyChanged(nameof(FloatingIconTopmostLabel));
            OnPropertyChanged(nameof(ShowScrollButtonsLabel));
            OnPropertyChanged(nameof(ShowDesktopIconLabel));
            OnPropertyChanged(nameof(StartDirectlyInLauncherLabel));
            OnPropertyChanged(nameof(StartDirectlyInLauncherDescription));
            OnPropertyChanged(nameof(LanguageLabel));
            OnPropertyChanged(nameof(ResetDefaultsLabel));
            OnPropertyChanged(nameof(EnableSlideUpAnimationLabel));
            OnPropertyChanged(nameof(EnableIconScrollLabel));
            OnPropertyChanged(nameof(CarouselViewLabel));
            OnPropertyChanged(nameof(WindowAnimationSpeedLabel));
            OnPropertyChanged(nameof(SettingsPlaceholderLabel));
            OnPropertyChanged(nameof(DevOverlayLabel));
            OnPropertyChanged(nameof(ChangeIconLabel));
            OnPropertyChanged(nameof(WindowsIconsLabel));
            OnPropertyChanged(nameof(OpenLabel));
            OnPropertyChanged(nameof(CloseLabel));
            OnPropertyChanged(nameof(MinimizeLabel));
            OnPropertyChanged(nameof(SelectLabel));
            OnPropertyChanged(nameof(ExitLabel));
            OnPropertyChanged(nameof(ExitFullyLabel));
            OnPropertyChanged(nameof(RunAsAdminLabel));
            OnPropertyChanged(nameof(OpenFileLocationLabel));
            OnPropertyChanged(nameof(CopyPathLabel));
            OnPropertyChanged(nameof(ResetIconLabel));
            OnPropertyChanged(nameof(RenameLabel));
            OnPropertyChanged(nameof(RemoveLabel));
            OnPropertyChanged(nameof(LayoutsLabel));
            OnPropertyChanged(nameof(MoreSettingsLabel));
            OnPropertyChanged(nameof(HelpLabel));
            OnPropertyChanged(nameof(AboutLabel));
            OnPropertyChanged(nameof(MonitorNetworkLabel));
            OnPropertyChanged(nameof(MonitorDownloadLabel));
            OnPropertyChanged(nameof(MonitorUploadLabel));
            OnPropertyChanged(nameof(MonitorCpuLabel));
            OnPropertyChanged(nameof(MonitorGpuLabel));
            OnPropertyChanged(nameof(HomeTitle));
            OnPropertyChanged(nameof(HomeIntroLine1));
            OnPropertyChanged(nameof(HomeIntroLine2));
            OnPropertyChanged(nameof(SystemAndStartupTitle));
            OnPropertyChanged(nameof(LanguageSectionTitle));
            OnPropertyChanged(nameof(LanguageSectionDescription));
            OnPropertyChanged(nameof(ToggleStatePrefixText));
            OnPropertyChanged(nameof(ToggleStateOnText));
            OnPropertyChanged(nameof(ToggleStateOffText));
            OnPropertyChanged(nameof(AlwaysOnTopDescription));
            OnPropertyChanged(nameof(ShowScrollButtonsDescription));
            OnPropertyChanged(nameof(DevOverlayDescription));
            OnPropertyChanged(nameof(UiScaleDescription));
            OnPropertyChanged(nameof(LanguageOptionDanish));
            OnPropertyChanged(nameof(LanguageOptionEnglish));
            OnPropertyChanged(nameof(ShortcutsTitle));
            OnPropertyChanged(nameof(ShortcutsIntro));
            OnPropertyChanged(nameof(ShortcutsAnimationTitle));
            OnPropertyChanged(nameof(ShortcutsAnimationIntro));
            OnPropertyChanged(nameof(ShortcutsAnimationToggle));
            OnPropertyChanged(nameof(AboutTitleText));
            OnPropertyChanged(nameof(AboutIntroText));
            OnPropertyChanged(nameof(HelpTitleText));
            OnPropertyChanged(nameof(HelpIntroText));
            OnPropertyChanged(nameof(HelpDragDropText));
            OnPropertyChanged(nameof(HelpSensorsText));
            OnPropertyChanged(nameof(HelpTopBarText));
            OnPropertyChanged(nameof(HelpMoreTipsText));
            OnPropertyChanged(nameof(LayoutTitleText));
            OnPropertyChanged(nameof(LayoutIntroText));
            OnPropertyChanged(nameof(LayoutPresetsTitleText));
            OnPropertyChanged(nameof(LayoutPresetsIntroText));
            OnPropertyChanged(nameof(LayoutFieldLabelText));
            OnPropertyChanged(nameof(LayoutRunNowText));
            OnPropertyChanged(nameof(LayoutSaveAsText));
            OnPropertyChanged(nameof(LayoutSkipMinimizedText));
            OnPropertyChanged(nameof(LayoutActiveScreenOnlyText));
            OnPropertyChanged(nameof(LayoutReserveSlotTitleText));
            OnPropertyChanged(nameof(LayoutReserveSlotIntroText));
            OnPropertyChanged(nameof(LayoutReserveSlotToggleText));
            OnPropertyChanged(nameof(LayoutChooseSlotText));
            OnPropertyChanged(nameof(LayoutPreviewPositionText));
            OnPropertyChanged(nameof(LayoutSlotTipText));
            OnPropertyChanged(nameof(LayoutPreviewTipText));
            OnPropertyChanged(nameof(HardwareNavTitleText));
            OnPropertyChanged(nameof(HardwareBoardTitleText));
            OnPropertyChanged(nameof(HardwareBoardIntroText));
            OnPropertyChanged(nameof(HardwareCpuIntroText));
            OnPropertyChanged(nameof(HardwareGpuIntroText));
            OnPropertyChanged(nameof(HardwareMemoryTitleText));
            OnPropertyChanged(nameof(HardwareMemoryIntroText));
            OnPropertyChanged(nameof(HardwareModelLabelText));
            OnPropertyChanged(nameof(HardwareSearchBoardLabelText));
            OnPropertyChanged(nameof(HardwareBiosLabelText));
            OnPropertyChanged(nameof(HardwareCoresLabelText));
            OnPropertyChanged(nameof(HardwareThreadsLabelText));
            OnPropertyChanged(nameof(HardwareLiveTempLabelText));
            OnPropertyChanged(nameof(HardwareLiveUsageLabelText));
            OnPropertyChanged(nameof(HardwareLiveClockLabelText));
            OnPropertyChanged(nameof(HardwareBoostLabelText));
            OnPropertyChanged(nameof(HardwareVendorLabelText));
            OnPropertyChanged(nameof(HardwareVramLabelText));
            OnPropertyChanged(nameof(HardwareLayoutLabelText));
            OnPropertyChanged(nameof(HardwareTypeLabelText));
            OnPropertyChanged(nameof(HardwareSpeedLabelText));
            OnPropertyChanged(nameof(HardwareTimingLabelText));
            OnPropertyChanged(nameof(HardwareModulesLabelText));
            OnPropertyChanged(nameof(HardwareSlotsLabelText));
            OnPropertyChanged(nameof(HardwareVoltageLabelText));
        }

        private void ApplyLocalizationState()
        {
            var pawnIoTextsChanged = _localizationState.ApplyLanguage(Language);
            NotifyLocalizationPropertiesChanged();

            if (pawnIoTextsChanged)
            {
                OnPropertyChanged(nameof(PawnIoMissingMessage));
                OnPropertyChanged(nameof(PawnIoDownloadLink));
            }
        }
    }
}