using System.Collections.Generic;

namespace IconGrid.Helpers.Settings;

public static class LocalizationHelper
{
    private static readonly Dictionary<string, Dictionary<string, string>> _resources = new()
    {
        ["en"] = new()
        {
            ["SettingsTitle"] = "Settings",
            ["IconsPerRow"] = "Icons per row",
            ["IconRowSpacing"] = "Icon row spacing",
            ["LastRowPadding"] = "Bottom padding (last row)",
            ["IconSize"] = "Icon size",
            ["UiScale"] = "UI size",
            ["AlwaysOnTop"] = "Always on top",
            ["FloatingIconTopmost"] = "Floating icon always on top",
            ["ShowScrollButtons"] = "Show scroll buttons",
            ["ShowDesktopIcon"] = "Show desktop icon",
            ["StartWithWindows"] = "Start with Windows",
            ["DevOverlayLabel"] = "Show developer overlays",
            ["Language"] = "Language",
            ["ResetDefaults"] = "Reset to defaults",
            ["SettingsPlaceholder"] = "Settings page placeholder.\nHere we will add real options later.",
            ["AddShortcut"] = "Add shortcut...",
            ["AddPowerShellShortcut"] = "Add PowerShell shortcut",
            ["Custom"] = "Custom...",
            ["AddWindowsShortcut"] = "Add Windows shortcut",
            ["AddAll"] = "Add all",
            ["ChangeIcon"] = "Change icon",
            ["WindowsIcons"] = "Windows icons (modern)",
            ["ClearCategory"] = "Clear category",
            ["ClearCategoryConfirm"] = "Are you sure you want to remove all icons in this category?",
            ["Open"] = "Open",
            ["Close"] = "Close",
            ["Minimize"] = "Minimize",
            ["Select"] = "Select",
            ["Exit"] = "Exit",
            ["RunAsAdmin"] = "Run as administrator",
            ["OpenFileLocation"] = "Open file location",
            ["CopyPath"] = "Copy path",
            ["ResetIcon"] = "Reset icon",
            ["Rename"] = "Rename",
            ["Remove"] = "Remove",
            ["EnableSlideUpAnimation"] = "Enable slide-up animation",
            ["WindowAnimationSpeed"] = "Window animation speed",
            ["EnableIconScroll"] = "Enable icon scroll",
            ["PawnIoMissingMessage"] = "CPU temperatures require PawnIO.",
            ["PawnIoDownloadLink"] = "Download PawnIO",
            ["MoreLayouts"] = "Layouts",
            ["MoreSettings"] = "Settings",
            ["MoreHelp"] = "Help",
            ["MoreAbout"] = "About",
            ["TabGames"] = "Games",
            ["TabSoftware"] = "Software",
            ["TabDevelop"] = "Develop",
            ["MonitorNetworkLabel"] = "Net",
            ["MonitorDownloadLabel"] = "↓ Download",
            ["MonitorUploadLabel"] = "↑ Upload",
            ["MonitorCpuLabel"] = "CPU",
            ["MonitorGpuLabel"] = "GPU",
            ["HomeTitle"] = "Home",
            ["HomeIntroLine1"] = "Manage general settings and how IconGrid interacts with your system.",
            ["HomeIntroLine2"] = "Configure startup, display, and core behavior from one place.",
            ["SystemAndStartupTitle"] = "System and startup",
            ["LanguageSectionTitle"] = "Language and region",
            ["LanguageSectionDescription"] = "Choose which language IconGrid uses across the launcher and settings pages.",
            ["ToggleStatePrefix"] = "",
            ["ToggleStateOn"] = "On",
            ["ToggleStateOff"] = "Off",
            ["AlwaysOnTopDescription"] = "IconGrid always stays above other windows",
            ["ShowScrollButtonsDescription"] = "Show scroll buttons on the category bar",
            ["DevOverlayDescription"] = "Show developer overlay",
            ["UiScaleDescription"] = "UI size",
            ["LanguageOptionDanish"] = "Dansk",
            ["LanguageOptionEnglish"] = "English",
            ["ShortcutsTitle"] = "Shortcut icons",
            ["ShortcutsIntro"] = "Fine-tune shortcut icon layout and spacing.",
            ["ShortcutsAnimationTitle"] = "Shortcut background slide animation",
            ["ShortcutsAnimationIntro"] = "Adjust the up/down animation and speed.",
            ["ShortcutsAnimationToggle"] = "Shortcut background animation",
            ["AboutTitle"] = "About IconGrid",
            ["AboutIntro"] = "Keep track of your icons, layouts, and detailed settings from one place.",
            ["HelpTitle"] = "Help",
            ["HelpIntro"] = "This guide explains how drag and drop and sensors work while IconGrid is running.",
            ["HelpDragDrop"] = "Drag and drop only works when IconGrid runs without administrator rights. Windows UIPI prevents Explorer from sending drag messages to windows with higher privileges.",
            ["HelpSensors"] = "When IconGrid runs without admin rights, LibreHardwareMonitor cannot read the CPU sensors, so temperatures remain '--'. If you need temperature data, run IconGrid as administrator and use the Add action by right-clicking an icon area in a category.",
            ["HelpMoreTips"] = "Need more tips? Use the other sections to find layout shortcuts and look for icons that match your workflow.",
            ["LayoutTitle"] = "Layout",
            ["LayoutIntro"] = "Fine-tune your window arrangement and save quick layout shortcuts in IconGrid.",
            ["LayoutPresetsTitle"] = "Default layout",
            ["LayoutPresetsIntro"] = "Choose the layout IconGrid should use when arranging open windows.",
            ["LayoutFieldLabel"] = "Layout",
            ["LayoutRunNow"] = "Run layout now",
            ["LayoutSaveAs"] = "Save layout as...",
            ["LayoutSkipMinimized"] = "Skip minimized windows",
            ["LayoutActiveScreenOnly"] = "Use active screen only",
            ["LayoutReserveSlotTitle"] = "Reserve IconGrid slot",
            ["LayoutReserveSlotIntro"] = "Choose the position IconGrid should use when reserving space in your layout.",
            ["LayoutReserveSlotToggle"] = "Reserve IconGrid slot",
            ["LayoutChooseSlot"] = "Choose icon slot",
            ["LayoutSlotTip"] = "Slot buttons are only active when the reserve toggle is enabled.",
            ["HardwareBoardTitle"] = "Motherboard",
            ["HardwareBoardIntro"] = "Overview of your motherboard and the active BIOS version.",
            ["HardwareCpuIntro"] = "Overview of the processor model, cores, boost speed, and live telemetry.",
            ["HardwareGpuIntro"] = "Overview of the graphics card model, vendor, video memory, and live telemetry.",
            ["HardwareMemoryTitle"] = "Memory",
            ["HardwareMemoryIntro"] = "Overview of RAM layout, type, speed, and timings.",
            ["HardwareModelLabel"] = "Model",
            ["HardwareBiosLabel"] = "BIOS",
            ["HardwareCoresLabel"] = "Cores",
            ["HardwareThreadsLabel"] = "Threads",
            ["HardwareLiveTempLabel"] = "Live temp",
            ["HardwareLiveUsageLabel"] = "Live usage",
            ["HardwareLiveClockLabel"] = "Live clock",
            ["HardwareBoostLabel"] = "Boost",
            ["HardwareVendorLabel"] = "Vendor",
            ["HardwareVramLabel"] = "VRAM",
            ["HardwareLayoutLabel"] = "Layout",
            ["HardwareTypeLabel"] = "Type",
            ["HardwareSpeedLabel"] = "Speed",
            ["HardwareTimingLabel"] = "Timing",
            ["HardwareModulesLabel"] = "Modules",
            ["HardwareVoltageLabel"] = "Voltage"
        },
        ["da"] = new()
        {
            ["SettingsTitle"] = "Indstillinger",
            ["IconsPerRow"] = "Ikoner pr. række",
            ["IconRowSpacing"] = "Mellemrum mellem ikonrækker",
            ["LastRowPadding"] = "Luft under sidste række",
            ["IconSize"] = "Ikonstørrelse",
            ["UiScale"] = "UI-størrelse",
            ["AlwaysOnTop"] = "Altid øverst",
            ["FloatingIconTopmost"] = "Flydende ikon altid øverst",
            ["ShowScrollButtons"] = "Vis rulleknapper",
            ["ShowDesktopIcon"] = "Vis skrivebordsikon",
            ["StartWithWindows"] = "Start med Windows",
            ["DevOverlayLabel"] = "Vis udvikler overlay",
            ["Language"] = "Sprog",
            ["ResetDefaults"] = "Nulstil til standarder",
            ["SettingsPlaceholder"] = "Indstillingsside placeholder.\nHer tilføjer vi rigtige valg senere.",
            ["AddShortcut"] = "Tilføj genvej...",
            ["AddPowerShellShortcut"] = "Tilføj PowerShell-genvej",
            ["Custom"] = "Brugerdefineret...",
            ["AddWindowsShortcut"] = "Tilføj Windows-genvej",
            ["AddAll"] = "Tilføj alle",
            ["ChangeIcon"] = "Skift ikon",
            ["WindowsIcons"] = "Windows-ikoner (moderne)",
            ["ClearCategory"] = "Ryd kategori",
            ["ClearCategoryConfirm"] = "Vil du fjerne alle ikoner i denne kategori?",
            ["Open"] = "Åbn",
            ["Close"] = "Luk",
            ["Minimize"] = "Minimer",
            ["Select"] = "Vælg",
            ["Exit"] = "Afslut",
            ["RunAsAdmin"] = "Kør som administrator",
            ["OpenFileLocation"] = "Åbn filplacering",
            ["CopyPath"] = "Kopier sti",
            ["ResetIcon"] = "Nulstil ikon",
            ["Rename"] = "Omdøb",
            ["Remove"] = "Fjern",
            ["EnableSlideUpAnimation"] = "Aktiver slide-op animation",
            ["WindowAnimationSpeed"] = "Vindues animationshastighed",
            ["EnableIconScroll"] = "Aktiver scroll",
            ["PawnIoMissingMessage"] = "CPU-temperaturer kræver PawnIO.",
            ["PawnIoDownloadLink"] = "Hent PawnIO",
            ["MoreLayouts"] = "Layouts",
            ["MoreSettings"] = "Indstillinger",
            ["MoreHelp"] = "Hjælp",
            ["MoreAbout"] = "Om",
            ["TabGames"] = "Spil",
            ["TabSoftware"] = "Software",
            ["TabDevelop"] = "Udvikling",
            ["MonitorNetworkLabel"] = "Net",
            ["MonitorDownloadLabel"] = "↓ Hent",
            ["MonitorUploadLabel"] = "↑ Send",
            ["MonitorCpuLabel"] = "CPU",
            ["MonitorGpuLabel"] = "GPU",
            ["HomeTitle"] = "Startside",
            ["HomeIntroLine1"] = "Administrer generelle indstillinger og hvordan IconGrid interagerer med dit system.",
            ["HomeIntroLine2"] = "Konfigurer opstart, visning og kernefunktioner fra et sted.",
            ["SystemAndStartupTitle"] = "System og opstart",
            ["LanguageSectionTitle"] = "Sprog og region",
            ["LanguageSectionDescription"] = "Vælg hvilket sprog IconGrid bruger i launcheren og på indstillingssiderne.",
            ["ToggleStatePrefix"] = "Slået",
            ["ToggleStateOn"] = "til",
            ["ToggleStateOff"] = "fra",
            ["AlwaysOnTopDescription"] = "IconGrid vises altid øverst",
            ["ShowScrollButtonsDescription"] = "Vis rulleknapper på kategori menuen",
            ["DevOverlayDescription"] = "Vis udvikler overlay",
            ["UiScaleDescription"] = "UI størrelse",
            ["LanguageOptionDanish"] = "Dansk",
            ["LanguageOptionEnglish"] = "English",
            ["ShortcutsTitle"] = "Genvejsikoner",
            ["ShortcutsIntro"] = "Finjuster layoutet af genvejsikoner og deres spacing.",
            ["ShortcutsAnimationTitle"] = "Genvejsikoner baggrunds slide op/ned animation",
            ["ShortcutsAnimationIntro"] = "Finjuster op/ned animation og hastighed.",
            ["ShortcutsAnimationToggle"] = "Genvejsikoner baggrunds animation",
            ["AboutTitle"] = "Om IconGrid",
            ["AboutIntro"] = "Hold styr på dine ikoner, layout og detaljerede indstillinger fra et sted.",
            ["HelpTitle"] = "Hjælp",
            ["HelpIntro"] = "Guiden forklarer, hvordan drag og drop og sensorer fungerer, når IconGrid kører.",
            ["HelpDragDrop"] = "Drag og drop fungerer kun, når IconGrid kører uden administratorrettigheder. Windows' UIPI forhindrer Explorer i at sende drag-beskeder til vinduer med højere privilegier.",
            ["HelpSensors"] = "Når IconGrid kører uden admin, kan LibreHardwareMonitor ikke læse CPU-sensorerne, så temperaturerne forbliver som '--'. Hvis du har brug for temperaturdata, kør IconGrid som administrator og brug Tilføj-handlingen ved at højreklikke på et ikonområde i en kategori.",
            ["HelpMoreTips"] = "Har du brug for flere tips? Brug de andre sektioner til at finde layout-genveje, og kig efter ikoner der matcher din workflow.",
            ["LayoutTitle"] = "Layout",
            ["LayoutIntro"] = "Finjuster opstillingen af dine vinduer og gem hurtige layout-genveje i IconGrid.",
            ["LayoutPresetsTitle"] = "Standard layout",
            ["LayoutPresetsIntro"] = "Vælg det layout, som IconGrid skal bruge til at arrangere åbne vinduer.",
            ["LayoutFieldLabel"] = "Layout",
            ["LayoutRunNow"] = "Kør layout nu",
            ["LayoutSaveAs"] = "Gem layout som...",
            ["LayoutSkipMinimized"] = "Spring minimerede vinduer over",
            ["LayoutActiveScreenOnly"] = "Brug kun den aktive skærm",
            ["LayoutReserveSlotTitle"] = "Reserver IconGrid-slot",
            ["LayoutReserveSlotIntro"] = "Vælg den position IconGrid skal bruge, når du reserverer plads i dit layout.",
            ["LayoutReserveSlotToggle"] = "Reserver IconGrid-slot",
            ["LayoutChooseSlot"] = "Vælg ikon-slot",
            ["LayoutSlotTip"] = "Slot-knapperne er kun aktive, når reserven er slået til.",
            ["HardwareBoardTitle"] = "Bundkort",
            ["HardwareBoardIntro"] = "Oversigt over dit bundkort og den aktive BIOS-version.",
            ["HardwareCpuIntro"] = "Oversigt over processorens model, kerner, boost-hastighed og live telemetri.",
            ["HardwareGpuIntro"] = "Oversigt over grafikkortets model, producent, videohukommelse og live telemetri.",
            ["HardwareMemoryTitle"] = "Hukommelse",
            ["HardwareMemoryIntro"] = "Oversigt over RAM-layout, type, hastighed og timing.",
            ["HardwareModelLabel"] = "Model",
            ["HardwareBiosLabel"] = "BIOS",
            ["HardwareCoresLabel"] = "Kerner",
            ["HardwareThreadsLabel"] = "Tråde",
            ["HardwareLiveTempLabel"] = "Live temp",
            ["HardwareLiveUsageLabel"] = "Live usage",
            ["HardwareLiveClockLabel"] = "Live clock",
            ["HardwareBoostLabel"] = "Boost",
            ["HardwareVendorLabel"] = "Producent",
            ["HardwareVramLabel"] = "VRAM",
            ["HardwareLayoutLabel"] = "Layout",
            ["HardwareTypeLabel"] = "Type",
            ["HardwareSpeedLabel"] = "Hastighed",
            ["HardwareTimingLabel"] = "Timing",
            ["HardwareModulesLabel"] = "Moduler",
            ["HardwareVoltageLabel"] = "Spænding"
        }
    };

    public static string Get(string language, string key)
    {
        if (string.IsNullOrWhiteSpace(language)) language = "en";
        if (_resources.TryGetValue(language.ToLowerInvariant(), out var dict) && dict.TryGetValue(key, out var value))
        {
            return value;
        }

        // fallback to en
        if (_resources["en"].TryGetValue(key, out var fallback))
        {
            return fallback;
        }

        return key;
    }
}
